# Generated by Django 5.1.1 on 2024-10-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'verbose_name_plural': 'Directores generales'},
        ),
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='NEGOCIOS', max_length=30, verbose_name='Especialidad del director'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='SANTIAGO', max_length=35, verbose_name='Ciudad de origen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='país',
            field=models.CharField(default='CHILE', max_length=35, verbose_name='País de origen'),
            preserve_default=False,
        ),
    ]
