# Generated by Django 5.1.1 on 2024-10-16 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_alter_laboratorio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratorio',
            options={},
        ),
    ]
