# Generated by Django 5.1.1 on 2024-10-18 13:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0006_alter_laboratorio_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('ver_margen', 'Puede ver el costo de producción y margen'), ('reponer_producto', 'Puede aumentar la cantidad de stock disponible del producto')]},
        ),
        migrations.AddField(
            model_name='producto',
            name='descripción',
            field=models.CharField(default='sin descripción', max_length=200, verbose_name='descripción producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='disponibles',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100, message='no se puede tener más de %(limit_value)s de este item en stock')], verbose_name='cantidad disponible'),
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='cantidad a comprar')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='laboratorio.producto', verbose_name='Compra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de la compra')),
            ],
        ),
    ]
