# Generated by Django 5.1.1 on 2024-10-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_extrauserinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinfo',
            name='dirección',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='dirección de envío'),
        ),
    ]
