# Generated by Django 5.1.1 on 2024-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_alter_extrauserinfo_dirección'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauserinfo',
            name='dirección',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección de envío'),
        ),
    ]
